"use strict";
import { colours } from "../styles/base";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  app: {
    backgroundColor: colours.bg,
    height: "100%",
    width: "100%",
  },
  scroll: {
    padding: 50,
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    fontSize: 35,
    marginBottom: 25,
    color: colours.accent1,
    fontFamily: "Poppins-Bold",
  },
  input: {
    width: "100%",
    borderColor: colours.accent4,
    borderWidth: 1,
    marginBottom: 10,
    padding: 10,
    color: colours.accent1,
    fontFamily: "Poppins-Regular",
  },
  input_focused: {
    borderColor: colours.accent4,
    borderWidth: 2,
  },
  button__container: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 10,
    alignItems: "center",
    marginTop: 10,
  },
  button: {
    width: "60%",
    alignItems: "center",
    backgroundColor: colours.accent4,
    padding: 8,
    borderRadius: 12,
    marginBottom: 5,
  },
  button__accent: {
    backgroundColor: colours.accent3,
  },
  button__text: {
    alignItems: "center",
    color: "#fff",
    fontFamily: "Poppins-Bold",
    fontSize: 18,
  },
  upload__button: {
    flex: 1,
    marginRight: 15,
    width: "40%",
    alignItems: "center",
    backgroundColor: colours.accent4,
    padding: 10,
    borderRadius: 5,
    marginBottom: 5,
  },
  camera__button: {
    flex: 1,
    width: "40%",
    alignItems: "center",
    backgroundColor: colours.accent4,
    padding: 10,
    borderRadius: 5,
    marginBottom: 5,
  },
  progressBarContainerHidden: {
    width: "100%",
    height: 20,
    backgroundColor: "grey",
    borderRadius: 20,
    marginBottom: 10,
    overflow: "hidden",
    opacity: 0,
  },
  progressBarContainerShow: {
    width: "100%",
    height: 20,
    backgroundColor: "grey",
    borderRadius: 20,
    marginBottom: 10,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: colours.accent2,
  },
  textHide: {
    width: 0,
    height: 0,
    overflow: "hidden",
    opacity: 0,
  },
  textShow: {
    overflow: "hidden",
    fontSize: 10,
    color: "red",
    marginBottom: 10,
  },
  generic__error: {
    overflow: "hidden",
    fontSize: 10,
    color: "red",
    marginTop: -7,
    alignItems: "center",
  },
  textInput: {
    width: "100%",
    borderColor: colours.accent4,
    borderWidth: 1,
    marginBottom: 10,
    padding: 10,
    color: colours.accent1,
  },
  errorText: {
    fontSize: 10,
    color: "red",
    marginBottom: 10,
  },
  errorInput: {
    borderColor: "red",
  },
  link: {
    color: colours.accent2,
    textDecorationLine: "underline",
    fontSize: 12,
    fontFamily: "Poppins-Regular",
  },
  firebase__error: {
    overflow: "hidden",
    fontSize: 10,
    color: "red",
    marginTop: -7,
    alignItems: "center",
  },
});
